In [1]:
l = [1,2,3,4,5,6]*2

In [2]:
l

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [6]:
l = [1,2,3,4,5,6,7,8,9,10]

In [7]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
a = np.array(l)

convert list into array

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
type(a)           

numpy.ndarray

In [11]:
a.ndim

1

In [12]:
whan we check the shape of array then we get the ouput in tuple

SyntaxError: invalid syntax (2717850937.py, line 1)

In [ ]:
a.shape            

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

 two rows dim

In [ ]:
a1.ndim                     

In [ ]:
it def as two row and three coloum

In [ ]:
 a1.shape              

In [ ]:
l = []    

In [ ]:
addition -[0,0,0]
multiplication - [1,1,1]

In [ ]:
a = np.ones(5)


In [ ]:
a

In [ ]:
a.dtype

In [ ]:
b = np.zeros(5)

In [ ]:
b

In [ ]:
a = np.ones(5,dtype = int)

In [ ]:
a

In [ ]:
a.dtype

In [ ]:
two dimension array create than

In [ ]:
a = np.ones((2,3))

In [ ]:
a

In [ ]:
a = np.ones((2,3),dtype = int)

In [ ]:
a

In [ ]:
a = np.ones((2,3,4),dtype = int)       

In [ ]:
a

In [13]:
a = np.ones((3,4,5),dtype = int)

In [14]:
a

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [15]:
a = np.ones(5)

In [16]:
a

array([1., 1., 1., 1., 1.])

In [17]:
a = np.ones(5,dtype = bool)

In [18]:
a

array([ True,  True,  True,  True,  True])

In [19]:
a = np.zeros(5,dtype = bool)

In [20]:
a

array([False, False, False, False, False])

In [21]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1,200)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [29]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.arange(12,200,5)        

array([ 12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,  67,  72,
        77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127, 132, 137,
       142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192, 197])

In [31]:
np.linspace(1,10,15)     

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [32]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
len(a)

10

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
al = a.reshape(2,5)      

In [56]:
al.ndim

2

In [59]:
al.reshape(10,1)    

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [60]:
al.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [61]:
b = np.arange(1,25).reshape(6,4)

In [62]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [63]:
b = np.arange(1,25).reshape(2,4,3)

In [64]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [65]:
b.ndim

3

In [66]:
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [67]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [68]:
b.flatten(order = 'f')     

array([ 1, 13,  4, 16,  7, 19, 10, 22,  2, 14,  5, 17,  8, 20, 11, 23,  3,
       15,  6, 18,  9, 21, 12, 24])

In [69]:
a = np.arange(1,17).reshape(4,4)

In [70]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
b.reshape(1,-1)      

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [72]:
b.reshape(-1,1)       

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [73]:
a.transpose()           

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [74]:
a = np.arange(1,10).reshape(3,3)

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
b = np.arange(1,10).reshape(3,3)

In [77]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [79]:
np.subtract(a,b)         

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
np.divide(a,b)                

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a.min()

1

In [84]:
a.max()

9

In [85]:
a.min(axis=1)

array([1, 4, 7])

In [86]:
a.max(axis = 0)

array([7, 8, 9])

In [87]:
a.max(axis = 1)          

array([3, 6, 9])

In [88]:
a.min(axis = 0)

array([1, 2, 3])

In [90]:
a.argmax()               

8

In [91]:
a.argmin()  

0

In [94]:
a.argmax(axis = 1)        

array([2, 2, 2], dtype=int64)

In [95]:
a.argmin(axis = 1)

array([0, 0, 0], dtype=int64)

In [96]:
np.sum(a)

45

In [97]:
np.sum(a, axis = 1)

array([ 6, 15, 24])

In [98]:
np.sum(a, axis = 0)

array([12, 15, 18])

In [99]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
np.trace(a)        

15

In [103]:
np.mean(a)         

5.0

In [104]:
np.std(a)

2.581988897471611

In [105]:
np.var(a)

6.666666666666667

In [106]:
np.sqrt(a)               

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [107]:
a = np.arange(1,101).reshape(10,10)

In [108]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [111]:
a[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [112]:
a[:3]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [113]:
a[3:6]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [114]:
a[3:6,3]          

array([34, 44, 54])

In [115]:
a[3:6,3:8]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [116]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [117]:
a[:,3:10:2]          as a step it works start from 3 and end it 10 idx in 2 steps

SyntaxError: invalid syntax (279585330.py, line 1)

In [118]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
a1 = np.arange(1,10).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
np.dot(a, a1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [123]:
a = np.arange(1 ,17).reshape(4, 4)
b = np.arange(17, 33).reshape(4, 4)


In [124]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [125]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [128]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [131]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [132]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [133]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [134]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [135]:
np.split(a, 4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [136]:
np.split(a,2)          

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [138]:
np.split(a, 2,axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [139]:
s = np.split(a, 2,axis = 1)
s

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [140]:
type(s)

list

In [143]:
s[0]                  

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [144]:
a = np.array([11,22,33,44,55,66,77])
a

array([11, 22, 33, 44, 55, 66, 77])

In [145]:
np.split(a,[2])

[array([11, 22]), array([33, 44, 55, 66, 77])]

In [146]:
a = np.array([11,22,33,44,55,66,77,45,33,46,333,12])
a

array([ 11,  22,  33,  44,  55,  66,  77,  45,  33,  46, 333,  12])

In [147]:
np.split(a, [2,17])

[array([11, 22]),
 array([ 33,  44,  55,  66,  77,  45,  33,  46, 333,  12]),
 array([], dtype=int32)]

In [149]:
np.random.random()

0.4853422425903632

In [150]:
np.random.random(5)

array([0.44071206, 0.23743663, 0.52315172, 0.64724744, 0.09907829])

In [151]:
np.random.random((2,3))

array([[0.436669  , 0.93752104, 0.86487588],
       [0.52446255, 0.63636983, 0.73583846]])

In [154]:
np.random.random((2,2,3))    

array([[[0.27447765, 0.16578029, 0.88076264],
        [0.1830201 , 0.40243942, 0.40859789]],

       [[0.54664675, 0.61756733, 0.08386828],
        [0.0172699 , 0.11624903, 0.49404066]]])

In [155]:
np.random.randint(15, size =(2,4))

array([[12, 13, 11, 11],
       [14, 14,  6,  6]])

In [156]:
np.random.randint(15, 45, size =(3,2,4))

array([[[31, 21, 15, 30],
        [24, 15, 41, 39]],

       [[41, 19, 44, 34],
        [20, 29, 40, 34]],

       [[25, 38, 41, 43],
        [28, 21, 24, 29]]])

In [157]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
np.random.choice(a)           

4

In [159]:
np.random.permutation(a)

array([4, 3, 6, 5, 7, 8, 2, 1, 9])

In [160]:
np.random.choice(a)

1

In [161]:
np.random.permutation(a)
np.random.choice(a)

8

In [162]:
np.random.uniform(1,100,250)

array([38.82072521, 11.24012615, 70.32737244, 23.38277889, 38.4459392 ,
       28.25092086, 21.87529036, 87.55464709,  4.02276364, 87.47032067,
       56.77149978, 92.5688035 , 14.44217751, 65.22666307, 10.8900756 ,
       13.06974297, 81.84260049, 34.83333375, 90.93399456, 19.60980445,
       66.94311657, 18.65260075, 29.56390009, 20.47582573, 29.11730259,
       54.72029986, 40.18172014, 55.87956713, 42.28249878, 36.90665217,
       70.5626484 , 12.38190235, 41.56655213, 79.24371029, 69.00287799,
       45.36587854, 49.44984659, 93.41046939, 72.52546694, 62.77595876,
       97.85625092, 84.72052455, 54.22528935, 67.37184529, 44.02871964,
       99.36231134, 17.30899328,  4.07123986, 86.78218362, 14.38374614,
       48.33814367, 66.13444013, 30.2675748 , 21.52713902, 82.52097322,
       32.52504549, 90.40314783, 39.42966071, 20.19918974, 59.8166571 ,
       92.54800936, 46.6808707 , 43.6191783 , 78.44345574, 23.64704035,
       14.02438488, 39.56211173, 95.32524159, 46.80877829, 99.55

In [165]:
np.random.normal(20, 5, 100)

array([23.50628891, 20.62398513, 22.54368139, 11.67784447, 18.22892841,
       22.13203904, 23.82217759, 17.67507446, 19.8492804 , 14.77050734,
       16.17078442, 22.69492952, 26.15746568, 16.4629216 , 24.42888129,
       14.72835302, 16.93040739, 16.827104  , 23.88570944, 12.26980105,
       13.27520068, 20.8612834 , 24.60033526, 21.14657249, 10.4109804 ,
       18.75874501, 13.06297867, 15.75657913, 18.17423618, 21.23602364,
       21.96558738, 14.7895423 , 18.58763844, 20.23689171, 26.70092716,
       20.81865168, 24.99086985, 23.44166644, 17.66293602, 15.93644047,
       20.02724649, 21.91525331, 19.72053413, 19.8162541 , 16.37675564,
       19.84832173, 23.71774339, 26.05761451, 29.18290331, 19.0898037 ,
       21.28686488, 13.82078548, 25.2921288 , 18.5238891 , 18.04220972,
       22.39264144, 15.83995492, 23.32133343, 19.89006711, 16.01068084,
       23.63133636, 16.23904073, 14.05645726, 22.36166244, 29.36107205,
       24.67968656, 17.00717713, 24.66722829, 21.04918263, 24.46

In [166]:
s = "python"
s1 = "data science"

In [167]:
np.char.add(s,s1)

array('pythondata science', dtype='<U18')

In [168]:
np.char.upper(s)

array('PYTHON', dtype='<U6')

In [169]:
np.char.lower(s)

array('python', dtype='<U6')

In [170]:
np.char.center(s,20, " ")

array('       python       ', dtype='<U20')

In [171]:
np.char.center(s,20, "*")

array('*******python*******', dtype='<U20')

In [172]:
np.char.split(s1)

array(list(['data', 'science']), dtype=object)